周一:
  启用: true
  name: 自定义  # 二楼东/二楼西/四楼/三楼大厅/守正书院/求新书院/自定义
  开始时间: 8
  持续小时数: 14
周二:
  启用: true
  name: 自定义
  开始时间: 8
  持续小时数: 14
周三:
  启用: true
  name: 自定义
  开始时间: 8
  持续小时数: 14
周四:
  启用: true
  name: 二楼西
  开始时间: 8
  持续小时数: 14
周五:
  启用: true
  name: 二楼西
  开始时间: 8
  持续小时数: 14
周六:
  启用: true
  name: 二楼西
  开始时间: 8
  持续小时数: 14
周日:
  启用: true
  name: 二楼西
  开始时间: 8
  持续小时数: 14

自定义:
    - 60856
    - 60860

############################################
#                 NOTICE
# 请注意，若要开启自定义功能，需将name改为“自定义” 
# 如无特殊需求（如固定座位），只需填对应自习室名称，
# 无需修改自定义中内容。
# 若需要固定位置，可以填写区间中的任意几个数值，
# 脚本会自动据此选择座位。
# 若希望后续开发根据座位号选座，可以开一个issue，
# 需求人数大于5人我就更新，当然我更欢迎大家pr:)
############################################
# 3东：42101-42140
# 3西：42141-42184
# 3北: 42185-42215
# 5： 43285-43455 （包括但不仅限于，json包懒得看，以下同理（（（（）
# 7： 42587-42700
# 8： 42710-42842
# 9： 42887-42978
# 10：43031-43114
# 11：43153-43266

